spring.application.name=event-ticket-platform

spring.config.import=optional:file:.env[.properties]

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Allows JSON "student" to be mapped to the UserRole.STUDENT enum
spring.jackson.mapper.accept-case-insensitive-enums=true

springdoc.api-docs.path=/api/v1/openapi
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=${JWT_SECRET:g3PstNObRVynsnHTJgfrPumK1I3bLosuBpS3COiI6OdoGBuEEuswbJ6HNzN7s4v4g60T8UennY+iqo1enOkicg==}
jwt.expiration-hours=24